import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import Game from '@/components/Game'



const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className=' flex flex-col min-h-screen min-w-full place-content-center bg-red-500'>
        <div className='flex flex-row place-content-center'>
        
        
        <Game/>
        </div>
        
          
        
      </main>
    </>
  )
}
